/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
// ------------------------------------------- Includes -------------------------------------------
#include <stdint.h>
#include "stm32f446xx.h"
#include "main.h"
#include "spi.h"
#include "gpio.h"
#include "usart.h"
#include "can.h"

// --------------------------------------- Private Function ---------------------------------------
int __io_putchar(int ch)
{
	while(((USART2->SR)&= (1<<7))==0);
	USART2->DR = ch;
}

// --------------------------------------------- Main ---------------------------------------------
int main(void)
{
	// Variable declaration
	uint8_t msg = 0;
	CAN_data can_data;
	uint32_t data = 0xFFFF;

	// Setup
	GPIO_Init();
	USART2_Init();
	SPI2_Init();
	CAN_init();

    /* Loop forever */
	for( ; ; )
	{
//		msg = USART2_Receive();
//		SPI2_Transmit(msg);
//		msg = SPI2_Receive();

		CAN_sendData_mailbox0(0x00, data);

//		can_data = CAN_receiveData();
//		msg = (uint8_t) can_data.dataL;
//		SPI2_Transmit(msg);
//		msg = SPI2_Receive();
//		USART2_Transmit(msg);
	}
}
